public with sharing class GlobalConstants
{
    // Application Log object - debug level
    public static final String LOG_LEVEL_DEBUG          = 'Debug';
    public static final String LOG_LEVEL_ERROR          = 'Error';
   
   
    public static final String ACCESSMODEREAD            = 'R';
    public static final String ACCESSMODEUPDATE            = 'U';
      public static final String ACCESSMODECREATE            = 'C';
      public static final String ACCESSMODEDELETE            = 'D';
      public static final String ACCESSMODECREATEUPDATE    = 'CU';
     
      public static final String TERM12                    = '12';
      public static final String TERM24                    = '24';
      public static final String TERM36                    = '36';
      public static final String TERM48                    = '48';
      public static final String TERM60                    = '60';
      public static final String TERM72                    = '72';
      public static final String TERM84                    = '84';
     
      public static final String FINANCE_LEASE_CALC        = 'Finance Lease';
      public static final String CHATTEL_MORTGAGE_CALC    = 'Chattel Mortgage';
      public static final String HIRE_PURCHASE_CALC        = 'Hire Purchase';
     
      public static final String MONTHLY                    = 'Monthly';
      public static final String QUATERLY                    = 'Quaterly';
        
}